"""
Sparse SFOI math core rebuilt to follow Durand et al. SFOI statistical model.

Key design choice for global basins
----------------------------------
This module keeps a sparse x = [Q_all, R_regions] formulation for scalability,
but it does NOT force source/headwater reaches to be generated by runoff.
Mass conservation equality constraints are built only for reaches that have
upstream reaches inside the current basin/domain. Therefore source reaches keep
independent discharge degrees of freedom, matching the role of Q_ind in the
paper.

The solver implements:
  * sparse weighted least squares for discharge/runoff observations;
  * Mike-style soft mass-balance rows by default, while retaining optional hard
    equality constraints for experiments;
  * an inner robust reweighting loop for outliers, following the paper/code
    adjust_lsq.py logic;
  * an outer multiplicative-error loop, following adjust_lsq_mult.py logic,
    W_i = 1 / (c_v_i * |theta_hat_i|), with practical theta/weight caps.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import scipy.sparse as sp
import cvxpy as cp
from scipy.stats.distributions import chi2


_EPS = np.finfo(float).eps
_W_MIN = 2.0 * np.sqrt(_EPS)


def _finite_summary(name: str, values: np.ndarray) -> str:
    arr = np.asarray(values, dtype=float).ravel()
    finite = arr[np.isfinite(arr)]
    if finite.size == 0:
        return f'{name}: count={arr.size}, finite=0'
    return (
        f'{name}: count={arr.size}, finite={finite.size}, '
        f'min={np.nanmin(finite):.6g}, p05={np.nanpercentile(finite, 5):.6g}, '
        f'median={np.nanmedian(finite):.6g}, p95={np.nanpercentile(finite, 95):.6g}, '
        f'max={np.nanmax(finite):.6g}'
    )


def _clip_weight_vector(W: np.ndarray, w_max: Optional[float] = None) -> np.ndarray:
    upper = np.inf if w_max is None or not np.isfinite(w_max) or w_max <= 0 else float(w_max)
    return np.clip(np.asarray(W, dtype=float), _W_MIN, upper)


@dataclass
class SparseSFOIResult:
    x: np.ndarray
    P: np.ndarray
    W: np.ndarray
    V: np.ndarray
    So: float
    index: np.ndarray
    delta: List[float]
    status: str
    outer_iterations: int
    inner_iterations: int
    diagnostics: List[dict]
    converged: bool = False


# -----------------------------------------------------------------------------
# Backward-compatible helpers retained from the old core
# -----------------------------------------------------------------------------

def calcG_sparse(m, n, junctions, basin_dict, reachlist='reach_ids_all'):
    rows, cols, data = [], [], []
    reach_map = {str(r): i for i, r in enumerate(basin_dict[reachlist])}

    for junction in junctions:
        row = junction['row_num']
        for upflow in junction['upflows']:
            if str(upflow) in reach_map:
                rows.append(row)
                cols.append(reach_map[str(upflow)])
                data.append(1.0)
        for downflow in junction['downflows']:
            if str(downflow) in reach_map:
                rows.append(row)
                cols.append(reach_map[str(downflow)])
                data.append(-1.0)
    return sp.csr_matrix((data, (rows, cols)), shape=(m, n))


def getA_sparse(C_sparse, n, D, l):
    I_n = sp.eye(n, format='csr')
    A = sp.bmat([[C_sparse], [I_n]], format='csr')
    A_lil = A.tolil()
    Dind = np.array([D[l + i] for i in range(n)])

    for i in range(l):
        nonzero_cols = A_lil.rows[i]
        if not nonzero_cols:
            continue
        sum_Dind = np.sum(Dind[nonzero_cols])
        if sum_Dind > 0:
            scale = D[i] / sum_Dind
            for idx in range(len(nonzero_cols)):
                A_lil.data[i][idx] *= scale
    return A_lil.tocsr()


def getP_1D(covQ, Qbar, norm=2):
    sigma_q = np.abs(np.array(Qbar, dtype=float)) * covQ
    sigma_q = np.clip(sigma_q, 1e-6, np.inf)
    return 1.0 / (sigma_q ** norm), 1.0 / (sigma_q ** (norm / 2.0))


# -----------------------------------------------------------------------------
# Sparse SFOI problem construction
# -----------------------------------------------------------------------------

def _as_reach_list(reach_ids: Sequence) -> List[str]:
    return [str(r) for r in reach_ids]


def _build_reach_index(reach_ids: Sequence) -> Dict[str, int]:
    return {str(r): i for i, r in enumerate(reach_ids)}


def _sword_row_index(sword_dict: dict) -> Dict[str, int]:
    return {str(int(r)): i for i, r in enumerate(sword_dict['reach_id'])}


def _get_sword_scalar(sword_dict: dict, sword_idx: Dict[str, int], reach: str, field: str, default=np.nan):
    try:
        return float(sword_dict[field][sword_idx[str(reach)]])
    except Exception:
        return default


def _build_upstream_contribs(
    reach_ids: Sequence,
    sword_dict: dict,
    junctions: Sequence[dict],
) -> Dict[str, List[Tuple[str, float]]]:
    """Return mapping downstream reach -> [(upstream reach, coefficient), ...].

    For normal confluences, coefficients are 1. For distributaries, the previous
    MOI logic partitions upstream flow by downstream width. This keeps that
    global-run compatible behavior while preserving sparse mass equations.
    """
    reach_list = _as_reach_list(reach_ids)
    reach_set = set(reach_list)
    sword_idx = _sword_row_index(sword_dict)
    up_contribs: Dict[str, List[Tuple[str, float]]] = {}

    if junctions:
        for junc in junctions:
            U = [str(u) for u in junc.get('upflows', []) if str(u) in reach_set and str(u) != '0']
            D = [str(d) for d in junc.get('downflows', []) if str(d) in reach_set and str(d) != '0']
            if not U or not D:
                continue

            widths = []
            for d in D:
                w = _get_sword_scalar(sword_dict, sword_idx, d, 'width', default=1.0)
                if not np.isfinite(w) or w <= 0:
                    w = 1.0
                widths.append(w)
            total_w = float(np.sum(widths))

            for idx, d in enumerate(D):
                p = widths[idx] / total_w if total_w > 0 else 1.0 / len(D)
                up_contribs.setdefault(d, [])
                for u in U:
                    up_contribs[d].append((u, float(p)))

    # Fallback: if some SWORD upstream links were not represented in junctions,
    # add them with coefficient 1.0.
    for reach in reach_list:
        if reach not in sword_idx:
            continue
        k = sword_idx[reach]
        try:
            n_up = int(sword_dict['n_rch_up'][k])
        except Exception:
            n_up = 0
        for j in range(n_up):
            try:
                up = str(int(sword_dict['rch_id_up'][j, k]))
            except Exception:
                continue
            if up == '0' or up not in reach_set:
                continue
            already = any(u == up for u, _ in up_contribs.get(reach, []))
            if not already:
                up_contribs.setdefault(reach, []).append((up, 1.0))

    return up_contribs


def assign_runoff_regions_by_prefix(reach_ids: Sequence, prefix_len: int = 6) -> Tuple[np.ndarray, List[str]]:
    """Assign runoff subregions using the first `prefix_len` digits of reach_id."""
    unique_regions: List[str] = []
    reach_regions: List[int] = []
    for reach in _as_reach_list(reach_ids):
        rid = str(reach)
        region = rid[:prefix_len] if len(rid) >= prefix_len else rid
        if region not in unique_regions:
            unique_regions.append(region)
        reach_regions.append(unique_regions.index(region))
    return np.asarray(reach_regions, dtype=int), unique_regions


def compute_delta_area_for_mass_rows(
    reach_ids: Sequence,
    sword_dict: dict,
    facc: np.ndarray,
    upstream_contribs: Dict[str, List[Tuple[str, float]]],
) -> np.ndarray:
    """Compute lateral drainage-area increment for each reach.

    For dependent reaches, delta_A = facc_current - weighted direct-upstream facc.
    For source reaches, this value is kept for diagnostics/prior construction but
    no mass row is built for them.
    """
    reach_list = _as_reach_list(reach_ids)
    reach_index = _build_reach_index(reach_list)
    delta_A = np.zeros(len(reach_list), dtype=float)

    for i, reach in enumerate(reach_list):
        fcur = float(facc[i]) if np.isfinite(facc[i]) else 0.0
        upstream_area = 0.0
        for up, coeff in upstream_contribs.get(reach, []):
            j = reach_index.get(str(up))
            if j is not None and np.isfinite(facc[j]):
                upstream_area += float(coeff) * float(facc[j])
        delta_A[i] = max(0.0, fcur - upstream_area)
    return delta_A


def compute_runoff_priors(
    Qbar: np.ndarray,
    facc: np.ndarray,
    reach_regions: np.ndarray,
    u_conversion: float,
    min_runoff: float = 1.0,
    fallback_runoff: float = 315.36,
) -> np.ndarray:
    """Compute regional runoff pseudo-observations from Q/facc.

    Units: Q [m3/s], facc [km2], u_conversion [m3/s per km2 per mm/yr],
    so R [mm/yr] = Q / (facc * u_conversion).
    """
    K = int(np.max(reach_regions)) + 1 if len(reach_regions) else 0
    R = np.full(K, np.nan, dtype=float)

    global_vals = []
    for i in range(len(Qbar)):
        if np.isfinite(Qbar[i]) and np.isfinite(facc[i]) and facc[i] > 0:
            val = float(Qbar[i]) / (float(facc[i]) * float(u_conversion))
            if np.isfinite(val) and val > 0:
                global_vals.append(val)

    global_fallback = float(np.nanmedian(global_vals)) if global_vals else fallback_runoff
    if not np.isfinite(global_fallback) or global_fallback <= 0:
        global_fallback = fallback_runoff

    for k in range(K):
        idx = np.where(reach_regions == k)[0]
        if idx.size == 0:
            R[k] = global_fallback
            continue

        facc_region = facc[idx]
        good_facc = facc_region[np.isfinite(facc_region) & (facc_region > 0)]
        facc_median = np.nanmedian(good_facc) if good_facc.size else np.inf

        valid = []
        for i in idx:
            if (
                np.isfinite(Qbar[i])
                and np.isfinite(facc[i])
                and facc[i] > 0
                and facc[i] <= facc_median
            ):
                valid.append(i)

        if not valid:
            valid = [i for i in idx if np.isfinite(Qbar[i]) and np.isfinite(facc[i]) and facc[i] > 0]

        vals = []
        for i in valid:
            val = float(Qbar[i]) / (float(facc[i]) * float(u_conversion))
            if np.isfinite(val) and val > 0:
                vals.append(val)

        R[k] = float(np.nanmedian(vals)) if vals else global_fallback
        if not np.isfinite(R[k]) or R[k] <= 0:
            R[k] = global_fallback

    return np.clip(R, min_runoff, np.inf)


def build_sparse_sfoi_problem(
    reach_ids: Sequence,
    sword_dict: dict,
    junctions: Sequence[dict],
    Qbar: np.ndarray,
    sigQ: np.ndarray,
    facc: np.ndarray,
    u_conversion: float,
    params_dict: Optional[dict] = None,
    prefix_len: int = 6,
) -> dict:
    """Build sparse SFOI observation matrix and dependent-reach mass constraints.

    Sparse formulation:
        x = [Q_1, ..., Q_n, R_1, ..., R_K]

    Observations:
        Q_i observed for all reaches, and R_k pseudo-observed for runoff regions.

    Mass constraints, only for dependent reaches:
        Q_i - sum_u c_ui Q_u - delta_A_i * u * R_region(i) = 0

    Source/headwater reaches intentionally do not receive a mass row; their Q_i
    remains an independent discharge degree of freedom, matching Q_ind in the
    paper's SFOI model.
    """
    params_dict = params_dict or {}
    reach_list = _as_reach_list(reach_ids)
    n = len(reach_list)
    Qbar = np.asarray(Qbar, dtype=float).reshape(n)
    sigQ = np.asarray(sigQ, dtype=float).reshape(n)
    facc = np.asarray(facc, dtype=float).reshape(n)

    reach_regions, region_labels = assign_runoff_regions_by_prefix(reach_list, prefix_len=prefix_len)
    K = len(region_labels)
    nvar = n + K

    upstream_contribs = _build_upstream_contribs(reach_list, sword_dict, junctions)
    delta_A = compute_delta_area_for_mass_rows(reach_list, sword_dict, facc, upstream_contribs)
    R_prior = compute_runoff_priors(Qbar, facc, reach_regions, u_conversion)

    # Observation matrix: first Q observations, then R pseudo-observations.
    I_q = sp.eye(n, nvar, format='csr')
    rows_R = np.arange(K)
    cols_R = n + np.arange(K)
    data_R = np.ones(K, dtype=float)
    A_R = sp.csr_matrix((data_R, (rows_R, cols_R)), shape=(K, nvar))
    A_obs = sp.vstack([I_q, A_R], format='csr')
    L_obs = np.concatenate([Qbar, R_prior])

    # Convert sigQ to coefficient of variation for multiplicative model.
    covQ = np.divide(sigQ, np.maximum(np.abs(Qbar), 1e-6), out=np.full(n, 1.0), where=np.isfinite(sigQ))
    covQ = np.asarray(covQ, dtype=float)
    covQ[~np.isfinite(covQ) | (covQ <= 0)] = params_dict.get('FLPE_Uncertainty', 0.6)
    covQ = np.clip(covQ, params_dict.get('SFOI_Min_CV', 0.02), params_dict.get('SFOI_Max_CV', 10.0))

    runoff_cv = params_dict.get('Runoff_Uncertainty', params_dict.get('SFOI_Runoff_Uncertainty', 0.5))
    covR = np.full(K, float(runoff_cv), dtype=float)
    cov_obs = np.concatenate([covQ, covR])

    # Equality-style mass rows are kept as diagnostics and can also be used as
    # Mike-style soft observation rows by appending them to A_obs. Their target
    # is zero, so a relative CV is not statistically meaningful. Encode an
    # explicit absolute sigma through the solver's multiplicative theta floor.
    theta_floor = max(float(params_dict.get('SFOI_Theta_Floor', 5.0)), 1.0e-6)
    legacy_mass_cv = float(
        params_dict.get('SFOI_Mass_CV', params_dict.get('SFOI_Soft_Mass_CV', 1.0))
    )
    soft_mass_sigma = float(
        params_dict.get('SFOI_Soft_Mass_Sigma', legacy_mass_cv * theta_floor)
    )
    if not np.isfinite(soft_mass_sigma) or soft_mass_sigma <= 0:
        raise ValueError('SFOI_Soft_Mass_Sigma must be finite and positive')
    mass_cov_at_floor = soft_mass_sigma / theta_floor

    # Equality constraints for dependent reaches only.
    reach_index = _build_reach_index(reach_list)
    eq_rows, eq_cols, eq_data = [], [], []
    eq_reach_indices: List[int] = []

    for i, reach in enumerate(reach_list):
        ups = upstream_contribs.get(reach, [])
        if not ups:
            # Source/independent reach: no mass constraint row.
            continue

        row = len(eq_reach_indices)
        eq_reach_indices.append(i)

        # + Q_i
        eq_rows.append(row)
        eq_cols.append(i)
        eq_data.append(1.0)

        # - sum coeff * Q_up
        for up, coeff in ups:
            j = reach_index.get(str(up))
            if j is None:
                continue
            eq_rows.append(row)
            eq_cols.append(j)
            eq_data.append(-float(coeff))

        # - delta_A * u * R_region
        reg = int(reach_regions[i])
        eq_rows.append(row)
        eq_cols.append(n + reg)
        eq_data.append(-float(delta_A[i]) * float(u_conversion))

    A_eq = sp.csr_matrix((eq_data, (eq_rows, eq_cols)), shape=(len(eq_reach_indices), nvar))
    b_eq = np.zeros(len(eq_reach_indices), dtype=float)

    A_sfoi = sp.vstack([A_obs, A_eq], format='csr') if A_eq.shape[0] > 0 else A_obs
    L_sfoi = np.concatenate([L_obs, np.zeros(A_eq.shape[0], dtype=float)])
    cov_sfoi = np.concatenate(
        [cov_obs, np.full(A_eq.shape[0], mass_cov_at_floor, dtype=float)]
    )

    # Nonnegative variables. Optional q minimum can be provided, but default is 0.
    q_min = float(params_dict.get('SFOI_Q_Min', 0.0))
    r_min = float(params_dict.get('SFOI_R_Min', 0.0))
    lb = np.concatenate([np.full(n, q_min), np.full(K, r_min)])
    ub = None

    # Starting point from observations.
    x0 = np.concatenate([np.clip(Qbar, max(q_min, 1e-6), np.inf), np.clip(R_prior, max(r_min, 1e-6), np.inf)])

    return {
        'A_obs': A_obs,
        'L_obs': L_obs,
        'cov_obs': cov_obs,
        'A_sfoi': A_sfoi,
        'L_sfoi': L_sfoi,
        'cov_sfoi': cov_sfoi,
        'A_eq': A_eq,
        'b_eq': b_eq,
        'lb': lb,
        'ub': ub,
        'x0': x0,
        'n_reaches': n,
        'K_regions': K,
        'region_labels': region_labels,
        'reach_regions': reach_regions,
        'delta_A': delta_A,
        'eq_reach_indices': np.asarray(eq_reach_indices, dtype=int),
        'upstream_contribs': upstream_contribs,
        'u_conversion': u_conversion,
        'R_prior': R_prior,
        'soft_mass_sigma': soft_mass_sigma,
    }


# -----------------------------------------------------------------------------
# Sparse weighted least squares and paper-style robust/multiplicative loops
# -----------------------------------------------------------------------------

def _clean_vector(name: str, x: np.ndarray, positive: bool = False) -> np.ndarray:
    x = np.asarray(x, dtype=float).ravel()
    if np.any(~np.isfinite(x)):
        raise ValueError(f'{name} contains NaN/Inf')
    if positive and np.any(x <= 0):
        raise ValueError(f'{name} must be positive')
    return x


def _solve_wls_sparse(
    A_obs: sp.spmatrix,
    L: np.ndarray,
    W: np.ndarray,
    A_eq: Optional[sp.spmatrix] = None,
    b_eq: Optional[np.ndarray] = None,
    lb: Optional[np.ndarray] = None,
    ub: Optional[np.ndarray] = None,
    x0: Optional[np.ndarray] = None,
    verbose: bool = False,
) -> Tuple[np.ndarray, str]:
    """Solve sparse constrained weighted least squares with quadratic loss."""
    L = _clean_vector('L', L)
    W = _clean_vector('W', W)
    if A_obs.shape[0] != L.size or L.size != W.size:
        raise ValueError('A_obs, L, and W have incompatible shapes')

    nvar = A_obs.shape[1]
    x = cp.Variable(nvar)
    residual = cp.multiply(W, A_obs @ x - L)
    objective = cp.Minimize(cp.sum_squares(residual))

    constraints = []
    if A_eq is not None and A_eq.shape[0] > 0:
        if b_eq is None:
            b_eq = np.zeros(A_eq.shape[0], dtype=float)
        constraints.append(A_eq @ x == np.asarray(b_eq, dtype=float).ravel())
    if lb is not None:
        lb = np.asarray(lb, dtype=float).ravel()
        finite_lb = np.where(np.isfinite(lb))[0]
        if finite_lb.size:
            constraints.append(x[finite_lb] >= lb[finite_lb])
    if ub is not None:
        ub = np.asarray(ub, dtype=float).ravel()
        finite_ub = np.where(np.isfinite(ub))[0]
        if finite_ub.size:
            constraints.append(x[finite_ub] <= ub[finite_ub])

    if x0 is not None:
        x0 = np.asarray(x0, dtype=float).ravel()
        if x0.size == nvar and np.all(np.isfinite(x0)):
            x.value = x0

    prob = cp.Problem(objective, constraints)

    solvers = []
    installed = set(cp.installed_solvers())
    for s in ('OSQP', 'CLARABEL', 'SCS'):
        if s in installed:
            solvers.append(s)

    last_error = None
    for solver in solvers:
        try:
            if solver == 'OSQP':
                prob.solve(
                    solver=cp.OSQP,
                    max_iter=100000,
                    eps_abs=1e-5,
                    eps_rel=1e-5,
                    adaptive_rho=True,
                    warm_start=True,
                    verbose=verbose,
                )
            elif solver == 'CLARABEL':
                prob.solve(solver=cp.CLARABEL, max_iter=20000, verbose=verbose)
            else:
                prob.solve(solver=cp.SCS, max_iters=50000, eps=1e-4, verbose=verbose)

            if prob.status in (cp.OPTIMAL, cp.OPTIMAL_INACCURATE) and x.value is not None:
                return np.asarray(x.value, dtype=float).ravel(), f'success_{solver.lower()}_{prob.status}'
            last_error = RuntimeError(f'{solver} status: {prob.status}')
        except Exception as exc:
            last_error = exc

    raise RuntimeError(f'Sparse WLS solver failed. Last error: {last_error}')


def adjust_lsq_sparse(
    A_sparse,
    W_1d,
    L,
    o=1,
    bound=True,
    idxbad=None,
    A_eq=None,
    b_eq=None,
    lb=None,
    ub=None,
):
    """Backward-compatible sparse WLS wrapper.

    Old calls solve min ||W(Ax-L)||^2 with optional Ax>=0. New calls may pass
    A_eq/lb/ub to solve the rebuilt sparse SFOI problem.
    """
    if lb is None and bound:
        lb = np.zeros(A_sparse.shape[1], dtype=float)
    if idxbad is not None:
        W_1d = np.asarray(W_1d, dtype=float).copy()
        W_1d[idxbad] = _W_MIN
    x, status = _solve_wls_sparse(A_sparse, L, W_1d, A_eq=A_eq, b_eq=b_eq, lb=lb, ub=ub)
    return x, status


def robust_inner_loop_sparse(
    A_obs: sp.spmatrix,
    L: np.ndarray,
    W_initial: np.ndarray,
    A_eq: Optional[sp.spmatrix] = None,
    b_eq: Optional[np.ndarray] = None,
    lb: Optional[np.ndarray] = None,
    ub: Optional[np.ndarray] = None,
    idxbad: Optional[Sequence[int]] = None,
    itermax: int = 15,
    limit: float = 2.5,
    alpha: float = 0.05,
    verbose: bool = False,
    theta_floor: float = 1e-6,
    w_max: Optional[float] = None,
    robust_eligible_mask: Optional[np.ndarray] = None,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, float, np.ndarray, np.ndarray, str, int]:
    """Paper-style inner loop with selectable robust-observation blocks.

    Protected rows (notably gages and soft mass rows) participate in the WLS
    solve and global chi-square statistic but cannot be declared outliers.
    """
    L = _clean_vector('L', L)
    W = _clean_vector('W_initial', W_initial).copy()
    W = _clip_weight_vector(W, w_max)
    if idxbad is not None and len(idxbad) > 0:
        W[np.asarray(idxbad, dtype=int)] = _W_MIN

    n_obs, n_var = A_obs.shape
    if robust_eligible_mask is None:
        robust_eligible = np.ones(n_obs, dtype=bool)
    else:
        robust_eligible = np.asarray(robust_eligible_mask, dtype=bool).ravel()
        if robust_eligible.size != n_obs:
            raise ValueError('robust_eligible_mask must have one value per observation row')
    n_eq = A_eq.shape[0] if A_eq is not None else 0
    dof = max(1, n_obs - n_var + n_eq)

    P = W ** 2
    good = np.full(n_obs, True, dtype=bool)
    s = np.zeros(n_obs, dtype=float)

    x_best = None
    V_best = np.full(n_obs, np.nan, dtype=float)
    So_best = np.nan
    status_best = 'failed'
    cst_pass = False

    iters = 0
    while (not cst_pass) and iters <= itermax:
        x, status = _solve_wls_sparse(A_obs, L, W, A_eq=A_eq, b_eq=b_eq, lb=lb, ub=ub, verbose=False)
        status_best = status
        x_best = x

        V = L - np.asarray(A_obs @ x).ravel()
        So_std = float(np.sqrt(max(np.dot(V, P * V) / dof, 0.0)))
        if not np.isfinite(So_std) or So_std <= 0:
            So_std = 1.0
        X = (So_std ** 2) * dof

        factor = (1.0 / _clip_weight_vector(W, w_max)) * So_std
        factor = np.clip(factor, max(float(theta_floor), 1e-12), np.inf)
        s = np.abs(V / factor)
        outlier = robust_eligible & (s > limit)
        good = ~outlier
        if idxbad is not None and len(idxbad) > 0:
            good[np.asarray(idxbad, dtype=int)] = False

        X_upper = chi2.ppf(1 - alpha / 2, dof)
        X_lower = chi2.ppf(alpha / 2, dof)

        # Outlier downweighting can only reduce the statistic. Applying it
        # below the lower chi-square bound drives the solution farther away
        # from the acceptance interval and can irreversibly erase good data.
        if X > X_upper:
            f = np.ones_like(L, dtype=float)
            f[outlier] = 10.0 ** (limit - s[outlier])
            f = np.clip(f, _EPS, np.inf)

            P = (f / factor) ** 2
            W = f / factor
            W = _clip_weight_vector(W, w_max)
            P = W ** 2

            if idxbad is not None and len(idxbad) > 0:
                W[np.asarray(idxbad, dtype=int)] = _W_MIN
                P[np.asarray(idxbad, dtype=int)] = _W_MIN

            if verbose:
                rejected = 100.0 * np.sum(~good) / max(1, n_obs)
                print(f'      [inner] iter={iters}, So={So_std:.4g}, rejected={rejected:.2f}%')
        else:
            cst_pass = True
            if verbose:
                position = 'below lower bound' if X < X_lower else 'inside bounds'
                print(
                    f'      [inner] stopped chi2 reweighting ({position}) '
                    f'with So={So_std:.4g}, iter={iters}'
                )

        V_best = V
        So_best = So_std ** 2
        iters += 1

    if x_best is None:
        raise RuntimeError('robust_inner_loop_sparse failed before producing a solution')

    return x_best, P, V_best, So_best, good, W, status_best, iters


def adjust_lsq_sparse_irls(
    A_sparse,
    W_1d,
    L,
    o=1,
    bound=True,
    idxbad=None,
    itermax=15,
    limit=2.5,
    A_eq=None,
    b_eq=None,
    lb=None,
    ub=None,
):
    """Backward-compatible IRLS wrapper returning x and status."""
    if lb is None and bound:
        lb = np.zeros(A_sparse.shape[1], dtype=float)
    x, P, V, So, index, W, status, _ = robust_inner_loop_sparse(
        A_sparse, L, W_1d, A_eq=A_eq, b_eq=b_eq, lb=lb, ub=ub,
        idxbad=idxbad, itermax=itermax, limit=limit,
    )
    return x, status


def adjust_lsq_mult_sparse(
    A_obs: sp.spmatrix,
    L: np.ndarray,
    cov: np.ndarray,
    A_eq: Optional[sp.spmatrix] = None,
    b_eq: Optional[np.ndarray] = None,
    lb: Optional[np.ndarray] = None,
    ub: Optional[np.ndarray] = None,
    x0: Optional[np.ndarray] = None,
    idxbad: Optional[Sequence[int]] = None,
    maxiter: int = 20,
    change_thresh: float = 0.05,
    inner_itermax: int = 15,
    outlier_limit: float = 2.5,
    alpha: float = 0.05,
    verbose: bool = False,
    theta_floor: float = 5.0,
    w_max: Optional[float] = 1.0e6,
    n_reaches: Optional[int] = None,
    n_regions: Optional[int] = None,
    n_soft_mass_rows: int = 0,
    n_gage_rows: int = 0,
    fixed_weight_mask: Optional[np.ndarray] = None,
    robust_eligible_mask: Optional[np.ndarray] = None,
) -> SparseSFOIResult:
    """Sparse multiplicative-error outer loop following Mike's reference code.

    The default caller now passes one sparse design matrix A_obs that can include
    normal Q/R observations plus soft mass-balance rows. Hard equality rows are
    still accepted for diagnostics/experiments, but are no longer required.
    """
    L = _clean_vector('L', L)
    cov = _clean_vector('cov', cov, positive=True)
    if L.size != cov.size or A_obs.shape[0] != L.size:
        raise ValueError('A_obs, L, and cov have incompatible shapes')

    if fixed_weight_mask is None:
        fixed_weight = np.zeros(L.size, dtype=bool)
    else:
        fixed_weight = np.asarray(fixed_weight_mask, dtype=bool).ravel()
        if fixed_weight.size != L.size:
            raise ValueError('fixed_weight_mask must have one value per observation row')

    if robust_eligible_mask is None:
        robust_eligible = np.ones(L.size, dtype=bool)
    else:
        robust_eligible = np.asarray(robust_eligible_mask, dtype=bool).ravel()
        if robust_eligible.size != L.size:
            raise ValueError('robust_eligible_mask must have one value per observation row')

    theta_floor = max(float(theta_floor), 1e-6)
    if w_max is not None:
        w_max = float(w_max)

    W = 1.0 / (cov * np.maximum(np.abs(L), theta_floor))
    W = _clip_weight_vector(W, w_max)
    fixed_weight_values = W.copy()
    if idxbad is not None and len(idxbad) > 0:
        W[np.asarray(idxbad, dtype=int)] = _W_MIN

    if x0 is None:
        x_old = np.ones(A_obs.shape[1], dtype=float)
    else:
        x_old = np.asarray(x0, dtype=float).ravel().copy()
        if x_old.size != A_obs.shape[1]:
            x_old = np.ones(A_obs.shape[1], dtype=float)
    x_old = np.clip(np.abs(x_old), theta_floor, np.inf)

    delta: List[float] = []
    diagnostics: List[dict] = []
    outliers_permanent: List[int] = []
    converged = False
    forced_weight_mixing = False
    status = 'failed'
    total_inner = 0

    x = None
    P = W ** 2
    V = np.full(L.size, np.nan)
    So = np.nan
    index = np.full(L.size, True, dtype=bool)

    for outer in range(maxiter):
        if verbose:
            print(f'      [outer] multiplicative iteration {outer}')
            print(f'      [outer] {_finite_summary("W_start", W)}')

        W_old = W.copy()
        if idxbad is not None and len(idxbad) > 0:
            W[np.asarray(idxbad, dtype=int)] = _W_MIN
        if outliers_permanent:
            W[np.asarray(outliers_permanent, dtype=int)] = _W_MIN

        x, P, V, So, index, W_inner, status, inner_iters = robust_inner_loop_sparse(
            A_obs=A_obs,
            L=L,
            W_initial=W,
            A_eq=A_eq,
            b_eq=b_eq,
            lb=lb,
            ub=ub,
            idxbad=idxbad,
            itermax=inner_itermax,
            limit=outlier_limit,
            alpha=alpha,
            verbose=verbose,
            theta_floor=theta_floor,
            w_max=w_max,
            robust_eligible_mask=robust_eligible,
        )
        total_inner += inner_iters

        denom = np.maximum(np.abs(x), theta_floor)
        d = float(np.sqrt(np.mean(((x - x_old) / denom) ** 2)))
        delta.append(d)
        if d < change_thresh:
            converged = True

        theta_hat = np.asarray(A_obs @ x).ravel()
        W = 1.0 / (cov * np.maximum(np.abs(theta_hat), theta_floor))
        W = _clip_weight_vector(W, w_max)
        W[fixed_weight] = fixed_weight_values[fixed_weight]

        n_bad_theta = int(np.sum(np.isfinite(theta_hat) & (np.abs(theta_hat) <= theta_floor)))
        n_outlier = int(np.sum(index == False))
        diag = {
            'outer': outer,
            'inner_iters': inner_iters,
            'delta': d,
            'So': float(So),
            'n_outlier': n_outlier,
            'n_bad_theta': n_bad_theta,
            'status': status,
            'min_theta': float(np.nanmin(theta_hat)) if np.any(np.isfinite(theta_hat)) else np.nan,
            'max_weight': float(np.nanmax(W)) if np.any(np.isfinite(W)) else np.nan,
        }
        diagnostics.append(diag)

        if verbose:
            print(
                '      [outer] summary '
                f"delta={d:.6g}, So={float(So):.6g}, outliers={n_outlier}, "
                f"theta<=floor={n_bad_theta}, status={status}"
            )
            print(f'      [outer] {_finite_summary("theta_hat", theta_hat)}')
            print(f'      [outer] {_finite_summary("x", x)}')
            print(f'      [outer] {_finite_summary("V", V)}')
            print(f'      [outer] {_finite_summary("W_next", W)}')
            if n_reaches is not None:
                print(f'      [outer] {_finite_summary("Q_solution", x[:int(n_reaches)])}')
            if n_reaches is not None and n_regions is not None:
                n0 = int(n_reaches)
                n1 = n0 + int(n_regions)
                print(f'      [outer] {_finite_summary("R_solution", x[n0:n1])}')
            if n_soft_mass_rows:
                mass_stop = len(V) - int(n_gage_rows) if n_gage_rows else len(V)
                mass_start = mass_stop - int(n_soft_mass_rows)
                print(f'      [outer] {_finite_summary("soft_mass_residual", V[mass_start:mass_stop])}')

        # Match Mike's reference-code engineering choices to stabilize late
        # multiplicative oscillations.
        if outer + 1 == 7:
            outliers_permanent = np.where((index == False) & robust_eligible)[0].tolist()
            if verbose:
                print(f'      [outer] fixing {len(outliers_permanent)} permanent outliers')
        if outer + 1 > 7 and outliers_permanent:
            W[np.asarray(outliers_permanent, dtype=int)] = _W_MIN
        if outer + 1 > 14 and not converged:
            wo = (outer + 1 - 14) / max(1, (maxiter - 1 - 14))
            wo = float(np.clip(wo, 0.0, 1.0))
            forced_weight_mixing = True
            if verbose:
                print(f'      [outer] Mike-style weight mixing old_weight={wo:.3f}')
            W = wo * W_old + (1.0 - wo) * W
            W = _clip_weight_vector(W, w_max)
            W[fixed_weight] = fixed_weight_values[fixed_weight]

        if converged:
            break
        x_old = x.copy()

    if x is None:
        raise RuntimeError('adjust_lsq_mult_sparse failed before producing a solution')

    final_index = index.copy()
    if outliers_permanent:
        final_index[np.asarray(outliers_permanent, dtype=int)] = False

    if converged:
        final_status = 'success_forced_converged' if forced_weight_mixing else 'success_converged'
    else:
        final_status = f'success_maxiter_{status}'

    return SparseSFOIResult(
        x=np.asarray(x, dtype=float).ravel(),
        P=np.asarray(P, dtype=float).ravel(),
        W=np.sqrt(np.asarray(P, dtype=float).ravel()),
        V=np.asarray(V, dtype=float).ravel(),
        So=float(So),
        index=final_index,
        delta=delta,
        status=final_status,
        outer_iterations=len(delta),
        inner_iterations=total_inner,
        diagnostics=diagnostics,
        converged=bool(converged),
    )


def adjust_lsq_bias_correlated_sparse(
    A_obs: sp.spmatrix,
    L: np.ndarray,
    cov: np.ndarray,
    n_reaches: int,
    n_regions: int,
    flpe_eligible_mask: Optional[np.ndarray] = None,
    correlation_groups: Optional[Sequence[int]] = None,
    correlation_rho: float = 0.0,
    bias_enabled: bool = True,
    bias_prior_std: Optional[float] = 0.5,
    bias_initial: float = 0.0,
    bias_min: float = -0.8,
    bias_max: float = 2.0,
    correlation_effect_bound: float = 8.0,
    A_eq: Optional[sp.spmatrix] = None,
    b_eq: Optional[np.ndarray] = None,
    lb: Optional[np.ndarray] = None,
    ub: Optional[np.ndarray] = None,
    x0: Optional[np.ndarray] = None,
    maxiter: int = 30,
    change_thresh: float = 1.0e-5,
    physical_rms_thresh: Optional[float] = None,
    physical_p95_thresh: Optional[float] = None,
    bias_thresh: Optional[float] = None,
    effect_thresh: Optional[float] = None,
    robust_thresh: Optional[float] = None,
    robust_limit: float = 3.0,
    alpha: float = 0.05,
    robust_damping: float = 0.5,
    oscillation_damping: float = 0.5,
    oscillation_direction_threshold: float = -0.5,
    minimum_step_relaxation: float = 0.05,
    relaxation_recovery: float = 1.25,
    relaxation_recovery_patience: int = 3,
    convergence_hold_iters: int = 3,
    max_So_at_convergence: float = 25.0,
    theta_floor: float = 5.0,
    w_max: Optional[float] = 1.0e6,
    fixed_weight_mask: Optional[np.ndarray] = None,
    robust_eligible_mask: Optional[np.ndarray] = None,
    verbose: bool = False,
) -> SparseSFOIResult:
    """Estimate physical flow, systematic FLPE bias, and sparse correlation effects.

    The first ``n_reaches`` rows of ``A_obs`` are reach-discharge priors and the
    first ``n_reaches`` state variables are physical reach discharge. Only rows
    selected by ``flpe_eligible_mask`` are genuine FLPE observations and receive
    the multiplicative bias/correlation augmentation:

        Q_flpe_i = (1 + b) Q_i + error_i.

    Runoff, mass-balance, and gage rows remain unbiased. Within-runoff-region
    correlation is represented as a Gaussian latent effect instead of a dense
    covariance matrix:

        error_i = sigma_i * (
            sqrt(rho) eta_region(i) + sqrt(1-rho) epsilon_i
        ),

    with independent standard-normal priors on every ``eta``. This is
    equivalent to block equicorrelation after marginalizing the latent effects,
    while preserving the sparse design needed for large basins.

    Prior/Fill discharge rows, runoff, mass-balance, and gage rows remain
    unbiased and uncorrelated. Variance scales are frozen during each
    Gauss-Newton/IRLS step. Gage and soft
    mass rows can be protected with ``fixed_weight_mask`` and
    ``robust_eligible_mask``. Robust downweighting is applied only when the
    global statistic is above the upper chi-square bound; low statistics cause
    weights to recover toward their nominal values. Strongly opposing
    consecutive Gauss-Newton directions indicate a fixed-point oscillation.
    Those steps are progressively under-relaxed, which collapses a period-two
    cycle toward its midpoint while preserving bounds and linear constraints.
    After several non-oscillating iterations, relaxation recovers gradually
    toward one.

    Convergence gates on the physical (Q, R) state only -- the part of the
    fit ``Qintegrator`` actually reads -- rather than on every auxiliary
    parameter. It declares convergence once the *applied* physical RMS and
    p95 step have both stayed under their thresholds for
    ``convergence_hold_iters`` consecutive iterations with a sane variance
    of unit weight (``So <= max_So_at_convergence``). Requiring the raw
    (undamped) candidate to also be tiny on a single iteration was tried
    first and rejected: relaxation's own oscillation-detection/recovery
    cycle can keep re-triggering on a fixed cadence indefinitely even after
    the physical state has stopped moving in any way that matters, which
    made that single-iteration, all-components gate self-perpetuating for
    several real basins. Requiring several *consecutive* good applied
    iterations is the standard, more robust substitute: it does not
    manufacture false convergence out of thin air (a fluke small step still
    has to repeat itself), and it does not depend on bias/effect/robust
    bookkeeping settling to the same numerical precision as the answer
    that is actually exported. Those components' own thresholds are still
    evaluated every iteration and recorded on ``result.diagnostics`` and
    ``result.fully_converged`` as a stricter, purely informational label.
    ``change_thresh`` remains a backward-compatible fallback for callers
    that do not supply the component thresholds.
    """
    A_obs = sp.csr_matrix(A_obs, dtype=float)
    L = _clean_vector('L', L)
    cov = _clean_vector('cov', cov, positive=True)
    n_obs, n_physical = A_obs.shape
    n_reaches = int(n_reaches)
    n_regions = int(n_regions)

    if L.size != n_obs or cov.size != n_obs:
        raise ValueError('A_obs, L, and cov have incompatible shapes')
    if n_reaches <= 0 or n_reaches + n_regions != n_physical:
        raise ValueError('physical state must be [Q_reaches, R_regions]')
    if n_obs < n_reaches:
        raise ValueError('A_obs does not contain all FLPE discharge rows')

    if flpe_eligible_mask is None:
        flpe_eligible = np.ones(n_reaches, dtype=bool)
    else:
        flpe_eligible = np.asarray(flpe_eligible_mask, dtype=bool).ravel()
        if flpe_eligible.size != n_reaches:
            raise ValueError(
                'flpe_eligible_mask must contain one value per reach row'
            )

    if bias_enabled and not np.any(flpe_eligible):
        raise ValueError('bias augmentation requires at least one genuine FLPE row')
    flpe_rows = np.flatnonzero(flpe_eligible)

    rho = float(correlation_rho)
    if not 0.0 <= rho < 1.0:
        raise ValueError('correlation_rho must satisfy 0 <= rho < 1')

    if fixed_weight_mask is None:
        fixed_weight = np.zeros(n_obs, dtype=bool)
    else:
        fixed_weight = np.asarray(fixed_weight_mask, dtype=bool).ravel()
        if fixed_weight.size != n_obs:
            raise ValueError('fixed_weight_mask must have one value per observation')

    if robust_eligible_mask is None:
        robust_eligible = np.ones(n_obs, dtype=bool)
    else:
        robust_eligible = np.asarray(robust_eligible_mask, dtype=bool).ravel()
        if robust_eligible.size != n_obs:
            raise ValueError(
                'robust_eligible_mask must have one value per observation'
            )
    robust_eligible &= ~fixed_weight

    use_correlation = rho > 0.0
    if use_correlation and not np.any(flpe_eligible):
        raise ValueError('correlation augmentation requires genuine FLPE rows')

    if correlation_groups is None:
        raw_groups = np.zeros(n_reaches, dtype=int)
    else:
        raw_groups = np.asarray(correlation_groups).ravel()
        if raw_groups.size != n_reaches:
            raise ValueError(
                'correlation_groups must have one entry per discharge reach'
            )

    # A Prior/Fill reach receives no latent correlation effect. Group indices
    # are therefore compacted over genuine FLPE rows only; -1 marks ineligible
    # reach rows in result diagnostics.
    group_index = np.full(n_reaches, -1, dtype=int)
    if use_correlation:
        _, eligible_inverse = np.unique(
            raw_groups[flpe_eligible], return_inverse=True
        )
        group_index[flpe_eligible] = np.asarray(eligible_inverse, dtype=int)
        n_correlation_groups = int(np.max(eligible_inverse)) + 1
    else:
        n_correlation_groups = 0
    n_bias = 1 if bias_enabled else 0
    bias_index = n_physical if bias_enabled else None
    effect_start = n_physical + n_bias
    n_augmented = effect_start + n_correlation_groups

    theta_floor = max(float(theta_floor), 1.0e-6)
    fallback_thresh = float(change_thresh)
    component_thresholds = {
        'physical_rms': float(
            fallback_thresh if physical_rms_thresh is None else physical_rms_thresh
        ),
        'physical_p95': float(
            fallback_thresh if physical_p95_thresh is None else physical_p95_thresh
        ),
        'bias': float(fallback_thresh if bias_thresh is None else bias_thresh),
        'effect': float(
            fallback_thresh if effect_thresh is None else effect_thresh
        ),
        'robust': float(
            fallback_thresh if robust_thresh is None else robust_thresh
        ),
    }
    if any(
        not np.isfinite(value) or value <= 0
        for value in component_thresholds.values()
    ):
        raise ValueError('all augmented convergence thresholds must be positive')
    robust_damping = float(np.clip(robust_damping, 0.0, 1.0))
    oscillation_damping = float(oscillation_damping)
    if not 0.0 < oscillation_damping <= 1.0:
        raise ValueError('oscillation_damping must satisfy 0 < value <= 1')
    oscillation_direction_threshold = float(oscillation_direction_threshold)
    if not -1.0 <= oscillation_direction_threshold < 0.0:
        raise ValueError(
            'oscillation_direction_threshold must satisfy -1 <= value < 0'
        )
    minimum_step_relaxation = float(minimum_step_relaxation)
    if not 0.0 < minimum_step_relaxation <= 1.0:
        raise ValueError(
            'minimum_step_relaxation must satisfy 0 < value <= 1'
        )
    relaxation_recovery = float(relaxation_recovery)
    if relaxation_recovery < 1.0 or not np.isfinite(relaxation_recovery):
        raise ValueError('relaxation_recovery must be finite and >= 1')
    relaxation_recovery_patience = int(relaxation_recovery_patience)
    if relaxation_recovery_patience < 1:
        raise ValueError('relaxation_recovery_patience must be >= 1')
    convergence_hold_iters = int(convergence_hold_iters)
    if convergence_hold_iters < 1:
        raise ValueError('convergence_hold_iters must be >= 1')
    max_So_at_convergence = float(max_So_at_convergence)
    if not np.isfinite(max_So_at_convergence) or max_So_at_convergence <= 0:
        raise ValueError('max_So_at_convergence must be finite and positive')
    effect_bound = max(float(correlation_effect_bound), 1.0)

    if x0 is None:
        x_physical = np.ones(n_physical, dtype=float)
    else:
        x_physical = np.asarray(x0, dtype=float).ravel().copy()
        if x_physical.size != n_physical or np.any(~np.isfinite(x_physical)):
            raise ValueError('x0 must contain one finite value per physical state')

    bias = float(np.clip(bias_initial, bias_min, bias_max)) if bias_enabled else 0.0
    effects = np.zeros(n_correlation_groups, dtype=float)
    robust_factor = np.ones(n_obs, dtype=float)

    if lb is None:
        physical_lb = np.full(n_physical, -np.inf, dtype=float)
    else:
        physical_lb = np.asarray(lb, dtype=float).ravel()
        if physical_lb.size != n_physical:
            raise ValueError('lb must contain one value per physical state')
    if ub is None:
        physical_ub = np.full(n_physical, np.inf, dtype=float)
    else:
        physical_ub = np.asarray(ub, dtype=float).ravel()
        if physical_ub.size != n_physical:
            raise ValueError('ub must contain one value per physical state')

    augmented_lb = np.concatenate(
        [
            physical_lb,
            np.array([bias_min], dtype=float) if bias_enabled else np.array([]),
            np.full(n_correlation_groups, -effect_bound, dtype=float),
        ]
    )
    augmented_ub = np.concatenate(
        [
            physical_ub,
            np.array([bias_max], dtype=float) if bias_enabled else np.array([]),
            np.full(n_correlation_groups, effect_bound, dtype=float),
        ]
    )

    A_eq_aug = None
    if A_eq is not None and A_eq.shape[0] > 0:
        A_eq = sp.csr_matrix(A_eq, dtype=float)
        if A_eq.shape[1] != n_physical:
            raise ValueError('A_eq must have one column per physical state')
        A_eq_aug = sp.hstack(
            [
                A_eq,
                sp.csr_matrix(
                    (A_eq.shape[0], n_bias + n_correlation_groups),
                    dtype=float,
                ),
            ],
            format='csr',
        )

    fixed_sigma = cov * np.maximum(np.abs(L), theta_floor)
    diagnostics: List[dict] = []
    delta: List[float] = []
    converged = False
    final_status = 'failed'
    final_residual = np.full(n_obs, np.nan, dtype=float)
    final_sigma_marginal = fixed_sigma.copy()
    final_chi2 = np.nan
    final_dof = max(
        1,
        n_obs - n_physical - n_bias + (A_eq.shape[0] if A_eq is not None else 0),
    )
    final_design = None
    final_weights = None
    previous_step_direction = None
    step_relaxation = 1.0
    oscillation_events = 0
    relaxation_recoveries = 0
    stable_relaxation_iterations = 0
    physical_stable_streak = 0
    convergence_mode = None
    last_fully_converged = False

    def assemble_state(
        physical: np.ndarray,
        bias_value: float,
        correlation_effects: np.ndarray,
    ) -> np.ndarray:
        parts = [np.asarray(physical, dtype=float).ravel()]
        if bias_enabled:
            parts.append(np.array([bias_value], dtype=float))
        if n_correlation_groups:
            parts.append(np.asarray(correlation_effects, dtype=float).ravel())
        return np.concatenate(parts)

    def marginal_sigma(
        physical: np.ndarray,
        bias_value: float,
        robust: np.ndarray,
    ) -> Tuple[np.ndarray, np.ndarray]:
        theta = np.asarray(A_obs @ physical).ravel()
        if bias_enabled:
            theta[:n_reaches] = physical[:n_reaches]
            theta[flpe_rows] *= 1.0 + bias_value
        else:
            theta[:n_reaches] = physical[:n_reaches]

        sigma = cov * np.maximum(np.abs(theta), theta_floor)
        sigma[fixed_weight] = fixed_sigma[fixed_weight]
        sigma = sigma / np.sqrt(np.clip(robust, _EPS, 1.0))
        sigma = np.clip(sigma, 1.0 / (w_max or np.inf), np.inf)

        sigma_independent = sigma.copy()
        if use_correlation:
            sigma_independent[flpe_rows] *= np.sqrt(1.0 - rho)
        return sigma, sigma_independent

    def prediction(
        physical: np.ndarray,
        bias_value: float,
        correlation_effects: np.ndarray,
        sigma: np.ndarray,
    ) -> np.ndarray:
        fitted = np.asarray(A_obs @ physical).ravel()
        fitted[:n_reaches] = physical[:n_reaches]
        if bias_enabled:
            fitted[flpe_rows] *= 1.0 + bias_value
        if n_correlation_groups:
            fitted[flpe_rows] += (
                sigma[flpe_rows]
                * np.sqrt(rho)
                * correlation_effects[group_index[flpe_rows]]
            )
        return fitted

    for outer in range(max(1, int(maxiter))):
        z_current = assemble_state(x_physical, bias, effects)
        sigma_marginal, sigma_independent = marginal_sigma(
            x_physical, bias, robust_factor
        )
        fitted = prediction(x_physical, bias, effects, sigma_marginal)

        J_x = A_obs.tolil(copy=True)
        if bias_enabled:
            for row in flpe_rows:
                J_x.data[row] = [
                    (1.0 + bias) * value for value in J_x.data[row]
                ]
        J_x = J_x.tocsr()

        columns = [J_x]
        if bias_enabled:
            J_bias = sp.csr_matrix(
                (
                    x_physical[flpe_rows],
                    (flpe_rows, np.zeros(flpe_rows.size, dtype=int)),
                ),
                shape=(n_obs, 1),
            )
            columns.append(J_bias)
        if n_correlation_groups:
            J_effect = sp.csr_matrix(
                (
                    sigma_marginal[flpe_rows] * np.sqrt(rho),
                    (flpe_rows, group_index[flpe_rows]),
                ),
                shape=(n_obs, n_correlation_groups),
            )
            columns.append(J_effect)

        J_data = sp.hstack(columns, format='csr')
        rhs_data = L - fitted + np.asarray(J_data @ z_current).ravel()
        data_weights = _clip_weight_vector(1.0 / sigma_independent, w_max)

        prior_rows = []
        prior_weights = []
        if bias_enabled and bias_prior_std is not None:
            bias_prior_std_value = float(bias_prior_std)
            if np.isfinite(bias_prior_std_value) and bias_prior_std_value > 0:
                prior_rows.append(
                    sp.csr_matrix(
                        ([1.0], ([0], [bias_index])),
                        shape=(1, n_augmented),
                    )
                )
                prior_weights.append(1.0 / bias_prior_std_value)
        if n_correlation_groups:
            prior_rows.append(
                sp.hstack(
                    [
                        sp.csr_matrix(
                            (n_correlation_groups, effect_start), dtype=float
                        ),
                        sp.eye(n_correlation_groups, format='csr'),
                    ],
                    format='csr',
                )
            )
            prior_weights.extend(np.ones(n_correlation_groups, dtype=float))

        if prior_rows:
            J_fit = sp.vstack([J_data, *prior_rows], format='csr')
            rhs_fit = np.concatenate(
                [rhs_data, np.zeros(sum(row.shape[0] for row in prior_rows))]
            )
            weights_fit = np.concatenate(
                [data_weights, np.asarray(prior_weights, dtype=float)]
            )
        else:
            J_fit = J_data
            rhs_fit = rhs_data
            weights_fit = data_weights

        z_candidate, solve_status = _solve_wls_sparse(
            J_fit,
            rhs_fit,
            weights_fit,
            A_eq=A_eq_aug,
            b_eq=b_eq,
            lb=augmented_lb,
            ub=augmented_ub,
            x0=z_current,
            verbose=False,
        )

        # Detect a fixed-point oscillation from the direction of consecutive
        # augmented-state updates. Scaling prevents large Q values from hiding
        # a reversal in the dimensionless bias or correlation effects.
        raw_step = np.asarray(z_candidate - z_current, dtype=float)
        direction_scale = np.ones(n_augmented, dtype=float)
        direction_scale[:n_physical] = np.maximum.reduce(
            [
                np.abs(z_current[:n_physical]),
                np.abs(z_candidate[:n_physical]),
                np.full(n_physical, theta_floor, dtype=float),
            ]
        )
        if bias_enabled:
            direction_scale[bias_index] = max(
                1.0,
                abs(float(z_current[bias_index])),
                abs(float(z_candidate[bias_index])),
            )
        if n_correlation_groups:
            direction_scale[effect_start:] = np.maximum.reduce(
                [
                    np.abs(z_current[effect_start:]),
                    np.abs(z_candidate[effect_start:]),
                    np.ones(n_correlation_groups, dtype=float),
                ]
            )

        raw_direction = raw_step / direction_scale
        raw_direction_norm = float(np.linalg.norm(raw_direction))
        raw_physical_scale = np.maximum(
            np.abs(z_candidate[:n_physical]), theta_floor
        )
        raw_physical_relative = np.abs(
            raw_step[:n_physical] / raw_physical_scale
        )
        raw_physical_delta = float(
            np.sqrt(np.mean(raw_physical_relative ** 2))
        )
        raw_physical_p95_delta = float(
            np.percentile(raw_physical_relative, 95)
        )
        raw_physical_max_delta = float(np.max(raw_physical_relative))
        raw_bias_delta = (
            abs(float(raw_step[bias_index])) if bias_enabled else 0.0
        )
        raw_effect_delta = (
            float(np.sqrt(np.mean(raw_step[effect_start:] ** 2)))
            if n_correlation_groups
            else 0.0
        )
        raw_iteration_delta = max(
            raw_physical_delta,
            raw_bias_delta,
            raw_effect_delta,
        )
        direction_cosine = np.nan
        oscillation_detected = False
        relaxation_recovered = False
        if previous_step_direction is not None and raw_direction_norm > _EPS:
            previous_norm = float(np.linalg.norm(previous_step_direction))
            if previous_norm > _EPS:
                direction_cosine = float(
                    np.dot(raw_direction, previous_step_direction)
                    / (raw_direction_norm * previous_norm)
                )
                if direction_cosine <= oscillation_direction_threshold:
                    oscillation_detected = True
                    oscillation_events += 1
                    stable_relaxation_iterations = 0
                    step_relaxation = max(
                        minimum_step_relaxation,
                        step_relaxation * oscillation_damping,
                    )

        if not oscillation_detected and step_relaxation < 1.0:
            stable_relaxation_iterations += 1
            if stable_relaxation_iterations >= relaxation_recovery_patience:
                recovered = min(1.0, step_relaxation * relaxation_recovery)
                relaxation_recovered = recovered > step_relaxation
                step_relaxation = recovered
                stable_relaxation_iterations = 0
                if relaxation_recovered:
                    relaxation_recoveries += 1
        elif step_relaxation >= 1.0:
            stable_relaxation_iterations = 0

        z_next = z_current + step_relaxation * raw_step
        z_next = np.minimum(np.maximum(z_next, augmented_lb), augmented_ub)
        applied_direction = (z_next - z_current) / direction_scale
        if raw_direction_norm > _EPS:
            previous_step_direction = applied_direction

        x_next = z_next[:n_physical]
        next_offset = n_physical
        if bias_enabled:
            bias_next = float(z_next[next_offset])
            next_offset += 1
        else:
            bias_next = 0.0
        effects_next = (
            np.asarray(z_next[next_offset:], dtype=float)
            if n_correlation_groups
            else np.array([], dtype=float)
        )

        physical_scale = np.maximum(np.abs(x_next), theta_floor)
        physical_relative = np.abs((x_next - x_physical) / physical_scale)
        physical_delta = float(np.sqrt(np.mean(physical_relative ** 2)))
        physical_p95_delta = float(np.percentile(physical_relative, 95))
        physical_max_delta = float(np.max(physical_relative))
        bias_delta = abs(bias_next - bias) if bias_enabled else 0.0
        effect_delta = (
            float(np.sqrt(np.mean((effects_next - effects) ** 2)))
            if n_correlation_groups
            else 0.0
        )
        iteration_delta = max(physical_delta, bias_delta, effect_delta)
        delta.append(iteration_delta)

        x_physical = x_next
        bias = bias_next
        effects = effects_next

        sigma_marginal, sigma_independent = marginal_sigma(
            x_physical, bias, robust_factor
        )
        fitted = prediction(x_physical, bias, effects, sigma_marginal)
        residual = L - fitted
        standardized = residual / sigma_independent

        chi2_stat = float(np.dot(standardized, standardized))
        if n_correlation_groups:
            chi2_stat += float(np.dot(effects, effects))
        if bias_enabled and bias_prior_std is not None:
            prior_std = float(bias_prior_std)
            if np.isfinite(prior_std) and prior_std > 0:
                chi2_stat += float((bias / prior_std) ** 2)

        dof = max(
            1,
            n_obs
            - n_physical
            - n_bias
            + (A_eq.shape[0] if A_eq is not None else 0),
        )
        chi2_low = float(chi2.ppf(alpha / 2, dof))
        chi2_high = float(chi2.ppf(1 - alpha / 2, dof))

        robust_before = robust_factor.copy()
        if chi2_stat > chi2_high:
            local_factor = np.ones(n_obs, dtype=float)
            local_standardized = np.abs(standardized)
            outlier = robust_eligible & (local_standardized > robust_limit)
            local_factor[outlier] = (
                robust_limit
                / np.maximum(local_standardized[outlier], 1.0e-12)
            ) ** 2
            robust_factor = (
                (1.0 - robust_damping) * robust_factor
                + robust_damping * local_factor
            )
        elif chi2_stat < chi2_low and np.any(robust_factor < 1.0):
            # Low chi-square means uncertainty is already too large. Restore
            # nominal weights instead of irreversibly downweighting more rows.
            robust_factor = (
                (1.0 - robust_damping) * robust_factor + robust_damping
            )
        robust_factor[~robust_eligible] = 1.0
        robust_factor = np.clip(robust_factor, _EPS, 1.0)
        robust_delta = float(np.max(np.abs(robust_factor - robust_before)))

        So = chi2_stat / dof
        diagnostic = {
            'outer': outer,
            'delta': iteration_delta,
            'physical_delta': physical_delta,
            'physical_p95_delta': physical_p95_delta,
            'physical_max_delta': physical_max_delta,
            'bias_delta': bias_delta,
            'effect_delta': effect_delta,
            'raw_delta': raw_iteration_delta,
            'raw_physical_delta': raw_physical_delta,
            'raw_physical_p95_delta': raw_physical_p95_delta,
            'raw_physical_max_delta': raw_physical_max_delta,
            'raw_bias_delta': raw_bias_delta,
            'raw_effect_delta': raw_effect_delta,
            'direction_cosine': direction_cosine,
            'oscillation_detected': oscillation_detected,
            'step_relaxation': step_relaxation,
            'relaxation_recovered': relaxation_recovered,
            'robust_delta': robust_delta,
            'So': So,
            'chi2_stat': chi2_stat,
            'chi2_low': chi2_low,
            'chi2_high': chi2_high,
            'chi2_pass': bool(chi2_low <= chi2_stat <= chi2_high),
            'bias_fraction': float(bias),
            'n_downweighted': int(np.sum(robust_factor < 0.999)),
            'solve_status': solve_status,
        }
        diagnostics.append(diagnostic)

        if verbose:
            print(
                '      [bias-correlation] '
                f'iter={outer + 1}, delta={iteration_delta:.6g}, '
                f'physical_rms={physical_delta:.6g}, '
                f'physical_p95={physical_p95_delta:.6g}, '
                f'raw={raw_iteration_delta:.6g}, robust={robust_delta:.6g}, '
                f'bias={bias:.6g}, So={So:.6g}, '
                f'downweighted={diagnostic["n_downweighted"]}, '
                f'rho={rho:.3g}, relaxation={step_relaxation:.3g}, '
                f'direction_cosine={direction_cosine:.3g}'
            )

        final_status = solve_status
        final_residual = residual
        final_sigma_marginal = sigma_marginal
        final_chi2 = chi2_stat
        final_dof = dof
        final_design = J_fit
        final_weights = weights_fit

        # Strict, single-iteration, all-components label: kept purely as a
        # diagnostic (see the docstring) -- it no longer gates whether a
        # result is accepted, since requiring the raw candidate to also be
        # tiny made this self-perpetuating whenever oscillation-detection
        # had to keep re-arming on a fixed cadence to hold a bounded,
        # low-amplitude cycle in check.
        physical_converged_strict = (
            physical_delta < component_thresholds['physical_rms']
            and raw_physical_delta < component_thresholds['physical_rms']
            and physical_p95_delta < component_thresholds['physical_p95']
            and raw_physical_p95_delta < component_thresholds['physical_p95']
        )
        bias_converged = (
            bias_delta < component_thresholds['bias']
            and raw_bias_delta < component_thresholds['bias']
        )
        effect_converged = (
            effect_delta < component_thresholds['effect']
            and raw_effect_delta < component_thresholds['effect']
        )
        robust_converged = robust_delta < component_thresholds['robust']
        fully_converged = (
            physical_converged_strict
            and bias_converged
            and effect_converged
            and robust_converged
        )
        diagnostic['physical_converged'] = physical_converged_strict
        diagnostic['bias_converged'] = bias_converged
        diagnostic['effect_converged'] = effect_converged
        diagnostic['robust_converged'] = robust_converged
        diagnostic['fully_converged'] = fully_converged
        last_fully_converged = fully_converged

        # Actual gate: the *applied* physical (Q, R) step -- what
        # Qintegrator is built from -- has to stay under its own RMS/p95
        # tolerance for several consecutive iterations, with a sane
        # variance of unit weight. This does not depend on the raw
        # candidate or on bias/effect/robust bookkeeping finishing at the
        # same precision, so a basin whose physical state has genuinely
        # settled is not held hostage by an oscillation-recovery cycle
        # still chasing its own tail on the side.
        physical_ok_applied = (
            physical_delta < component_thresholds['physical_rms']
            and physical_p95_delta < component_thresholds['physical_p95']
        )
        physical_stable_streak = (
            physical_stable_streak + 1 if physical_ok_applied else 0
        )
        diagnostic['physical_stable_streak'] = physical_stable_streak
        so_sane = np.isfinite(So) and So <= max_So_at_convergence

        if fully_converged:
            converged = True
            convergence_mode = 'strict'
        elif physical_stable_streak >= convergence_hold_iters and so_sane:
            converged = True
            convergence_mode = 'physical_hold'

        if converged:
            break

    if final_design is None or final_weights is None:
        raise RuntimeError('bias-correlated solver failed before producing a solution')

    bias_std = np.nan
    if bias_enabled:
        try:
            weighted_design = sp.diags(final_weights) @ final_design
            normal = (weighted_design.T @ weighted_design).tocsc()
            normal = normal + sp.eye(normal.shape[0], format='csc') * 1.0e-12
            selector = np.zeros(n_augmented, dtype=float)
            selector[bias_index] = 1.0
            column = sp.linalg.spsolve(normal, selector)
            if np.isfinite(column[bias_index]) and column[bias_index] >= 0:
                bias_std = float(np.sqrt(column[bias_index]))
        except Exception:
            bias_std = np.nan

    W_return = _clip_weight_vector(1.0 / final_sigma_marginal, w_max)
    convergence_label = (
        'converged_after_relaxation' if oscillation_events else 'converged_naturally'
    )
    result = SparseSFOIResult(
        x=np.asarray(x_physical, dtype=float).ravel(),
        P=W_return ** 2,
        W=W_return,
        V=np.asarray(final_residual, dtype=float).ravel(),
        So=float(final_chi2 / final_dof),
        index=np.asarray(robust_factor >= 0.999, dtype=bool),
        delta=delta,
        status=(
            f'success_bias_correlated_{convergence_label}_{final_status}'
            if converged
            else f'failed_bias_correlated_maxiter_{final_status}'
        ),
        outer_iterations=len(delta),
        inner_iterations=0,
        diagnostics=diagnostics,
        converged=bool(converged),
    )
    # Keep the historical result interface intact while exposing augmented
    # diagnostics to Integrate.py and downstream callers. ``convergence_mode``
    # distinguishes the strict (all-components) exit from the physical-hold
    # one the status string does not spell out.
    result.convergence_mode = (convergence_mode or 'maxiter') if converged else 'maxiter'
    result.fully_converged = bool(last_fully_converged)
    result.physical_stable_streak = int(physical_stable_streak)
    result.bias = float(bias)
    result.bias_std = float(bias_std)
    result.bias_enabled = bool(bias_enabled)
    result.correlation_rho = float(rho)
    result.correlation_groups = np.asarray(group_index, dtype=int)
    result.correlation_effects = np.asarray(effects, dtype=float)
    result.robust_factor = np.asarray(robust_factor, dtype=float)
    result.oscillation_events = int(oscillation_events)
    result.relaxation_recoveries = int(relaxation_recoveries)
    result.step_relaxation = float(step_relaxation)
    result.flpe_eligible_mask = np.asarray(flpe_eligible, dtype=bool)
    result.convergence_thresholds = dict(component_thresholds)
    result.flpe_prediction = x_physical[:n_reaches].copy()
    if bias_enabled:
        result.flpe_prediction[flpe_rows] *= 1.0 + bias
    return result


def estimate_q_uncertainty_rel(
    result: SparseSFOIResult,
    n_reaches: int,
    Qhat: np.ndarray,
    fallback_rel: float = 0.6,
) -> np.ndarray:
    """Cheap Output.py-compatible relative uncertainty proxy.

    Full paper covariance requires solving/inverting a large constrained normal
    matrix. For global sparse runs this function stores a conservative diagonal
    proxy from final observation weights and variance of unit weight.
    """
    Qhat = np.asarray(Qhat, dtype=float).ravel()
    W = np.asarray(result.W, dtype=float).ravel()
    So_std = np.sqrt(result.So) if np.isfinite(result.So) and result.So > 0 else 1.0

    rel = np.full(n_reaches, float(fallback_rel), dtype=float)
    usable = W[:n_reaches] > _W_MIN
    sigma = np.full(n_reaches, np.nan, dtype=float)
    sigma[usable] = So_std / np.maximum(W[:n_reaches][usable], _W_MIN)
    rel[usable] = sigma[usable] / np.maximum(np.abs(Qhat[usable]), 1e-6)
    rel[~np.isfinite(rel)] = float(fallback_rel)
    return np.clip(rel, 0.0, 10.0)


# Old strict-mass function retained for imports/backward compatibility only.
def adjust_lsq_sparse_strict_mass(A_sparse, W_1d, L, n_mass_rows, bound=True):
    mA, nA = A_sparse.shape
    n_prior_rows = mA - n_mass_rows
    A_prior = A_sparse[:n_prior_rows, :]
    A_mass = A_sparse[n_prior_rows:, :]
    W_prior = np.asarray(W_1d[:n_prior_rows], dtype=float)
    L_prior = np.asarray(L[:n_prior_rows], dtype=float)
    lb = np.zeros(nA) if bound else None
    try:
        x, status = _solve_wls_sparse(A_prior, L_prior, W_prior, A_eq=A_mass, b_eq=np.zeros(A_mass.shape[0]), lb=lb)
        return x, status
    except Exception as exc:
        print(f'      [Strict Mass Solver] failed: {exc}')
        return None, 'failed'
